import Quantum.State

namespace Quantum

namespace Measurement

/-- A family of measurement operators is complete when the effects sum to identity. -/
def IsComplete {n outcomes : ℕ} (M : Fin outcomes → Square n) : Prop :=
  (∑ m : Fin outcomes, (M m)† ⬝ M m) = I n

/-- Generalized measurement operators satisfying the completeness condition. -/
structure Generalized (n outcomes : ℕ) where
  operator : Fin outcomes → Square n
  isComplete : IsComplete operator

/-- Projection operators associated with an arbitrary family of state vectors. -/
noncomputable def projectiveOperators {n outcomes : ℕ}
    (u : Fin outcomes → Vector n) : Fin outcomes → Square n :=
  fun i => Matrix.proj (u i)

/-- A family of vectors defines a complete projective measurement when its projectors are complete. -/
def IsProjectiveComplete {n outcomes : ℕ} (u : Fin outcomes → Vector n) : Prop :=
  IsComplete (projectiveOperators u)

/-- Probability for a projective measurement generated by vector projectors. -/
noncomputable def projProb {n outcomes : ℕ}
    (u : Fin outcomes → Vector n) (s : Vector n) (i : Fin outcomes) : ℝ :=
  ((s† ⬝ Matrix.proj (u i) ⬝ s) 0 0).re

/-- Post-measurement state for a projective measurement generated by vector projectors. -/
noncomputable def projPostMeasure {n outcomes : ℕ}
    (u : Fin outcomes → Vector n) (s : Vector n) (i : Fin outcomes) : Vector n :=
  ((1 / Real.sqrt (projProb u s i) : ℝ) : ℂ) • (Matrix.proj (u i) ⬝ s)

namespace Generalized

variable {n outcomes : ℕ}

instance : CoeFun (Generalized n outcomes) (fun _ => Fin outcomes → Square n) where
  coe M := M.operator

@[simp]
theorem coe_apply (M : Generalized n outcomes) (m : Fin outcomes) :
    (M : Fin outcomes → Square n) m = M.operator m :=
  rfl

/-- Probability of generalized measurement outcome `m`. -/
noncomputable def prob (M : Generalized n outcomes) (s : Vector n) (m : Fin outcomes) : ℝ :=
  generalizedProb M.operator s m

/-- Normalized post-measurement state after generalized measurement outcome `m`. -/
noncomputable def postMeasure
    (M : Generalized n outcomes) (s : Vector n) (m : Fin outcomes) : Vector n :=
  generalizedPostMeasure M.operator s m

/-- Probability of outcome `m` for a pure state. -/
noncomputable def pureProb (M : Generalized n outcomes) (ψ : PureState n)
    (m : Fin outcomes) : ℝ :=
  M.prob ψ.vector m

/-- Post-measurement vector after measuring a pure state. -/
noncomputable def purePostMeasure (M : Generalized n outcomes) (ψ : PureState n)
    (m : Fin outcomes) : Vector n :=
  M.postMeasure ψ.vector m

end Generalized

/-- Complete projective measurement generated by a family of state-vector projectors. -/
structure Projective (n outcomes : ℕ) where
  vector : Fin outcomes → Vector n
  isUnit : ∀ i, Matrix.isUnit (vector i)
  isComplete : IsProjectiveComplete vector

namespace Projective

variable {n outcomes : ℕ}

instance : CoeFun (Projective n outcomes) (fun _ => Fin outcomes → Vector n) where
  coe M := M.vector

@[simp]
theorem coe_apply (M : Projective n outcomes) (m : Fin outcomes) :
    (M : Fin outcomes → Vector n) m = M.vector m :=
  rfl

noncomputable def operator (M : Projective n outcomes) : Fin outcomes → Square n :=
  projectiveOperators M.vector

/-- View a complete projective measurement as a generalized measurement. -/
noncomputable def toGeneralized (M : Projective n outcomes) : Generalized n outcomes where
  operator := M.operator
  isComplete := M.isComplete

/-- Probability of projective measurement outcome `m`. -/
noncomputable def prob (M : Projective n outcomes) (s : Vector n) (m : Fin outcomes) : ℝ :=
  projProb M.vector s m

/-- Normalized post-measurement state after projective measurement outcome `m`. -/
noncomputable def postMeasure
    (M : Projective n outcomes) (s : Vector n) (m : Fin outcomes) : Vector n :=
  projPostMeasure M.vector s m

end Projective

end Measurement

end Quantum
